name: Deploy Azure Landing Zones

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        customer: [contoso, globex]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/setup-azure@v1
        with:
          azure-cli-version: 'latest'

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep template
        run: |
          az deployment group create \
            --resource-group myResourceGroup \
            --template-file bicep/alz-main/modules/main.bicep \
            --parameters @customers/greenfield/contoso/parameters.json \
            --parameters @customers/brownfield/globex/parameters.json
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}